// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
package org.jellyfin.sdk.model.api

import kotlin.Int
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class ProblemDetails(
	@SerialName("Type")
	public val type: String? = null,
	@SerialName("Title")
	public val title: String? = null,
	@SerialName("Status")
	public val status: Int? = null,
	@SerialName("Detail")
	public val detail: String? = null,
	@SerialName("Instance")
	public val instance: String? = null,
)
